cal/urls.py
from django.urls import path
from . import views
from cal.views import CalendarView

# app_name = "cal"
urlpatterns = [
    path("index", views.index, name="index"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
]

payments/urls.py
from django.urls import path
from payments.views import PaymentsListView, PaymentCreateView

urlpatterns = [
    path("mypayments/", PaymentsListView.as_view(), name="payments_list"),
    path("createpayment/", PaymentCreateView.as_view(), name="create_payment"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("payments/", include("payments.urls")),
    path("", include("cal.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

cal/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return self.name

payments/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Payment(models.Model):
    name = models.CharField(max_length=100)
    amount = models.IntegerField(null=True)
    date_due = models.DateField()
    # how to set due date to a recurring day/month or custom
    owner = models.ForeignKey(User, related_name="payments", on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    category = models.CharField(max_length=100, null=True)
    recurring = models.BooleanField(default=False)

    def __str__(self):
        return self.name

subscriptions/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

cal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.views import generic
from django.utils.safestring import mark_safe

from .models import *
from .utils import Calendar


# Create your views here.
def index(request):
    return HttpResponse("hello")


class CalendarView(generic.ListView):
    model = Event
    template_name = "cal/calendar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get("day", None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context["calendar"] = mark_safe(html_cal)
        return context

        d = get_date(self.request.GET.get("month", None))
        context["prev_month"] = prev_month(d)
        context["next_month"] = next_month(d)
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split("-"))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = "month=" + str(next_month.year) + "-" + str(next_month.month)
    return month

payments/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from payments.models import Payment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.
class PaymentsListView(LoginRequiredMixin, ListView):
    model = Payment
    template_name = "payments/payments_list.html"

    def get_queryset(self):
        return Payment.objects.filter(owner=self.request.user)


class PaymentCreateView(LoginRequiredMixin, CreateView):
    model = Payment
    template_name = "payments/create_payment.html"
    fields = [
        "name",
        "amount",
        "date_due",
        "owner",
        "description",
        "category",
        "recurring",
    ]

    def get_success_url(self):
        return reverse_lazy("payments_list")

subscriptions/views.py
from django.shortcuts import render

# Create your views here.

cal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"> 
         
        <title>Tracker</title>
        
    </head>

    <body>
        <header>
            <h1>get organised!</h1>
            <nav>
                <ul>
                    {% comment %} {% if user.is_authenticated %} {% endcomment %}
                        <li>
                            <a href="{% url 'calendar' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'payments_list' %}">Payments</a>
                            {% comment %} <a href="{% url 'logout' %}">Logout</a> {% endcomment %}
                        </li>
                    {% comment %} {% else %}
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %} {% endcomment %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>

</html>

cal/templates/cal/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{'% url 'calendar' %'} {{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{'% url 'calendar' %'}{{ next_month }}"> Next Month </a>
</div>
{{ calendar }}
{% endblock %}

payments/templates/payments/create_payment.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Add New Payment</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

payments/templates/payments/payments_list.html
{% extends 'base.html' %}

{% block content %}
<body>
    <main>
        <aside><a href="{% url "create_payment" %}">Create payment</a></aside>
        <div>
            <h2>My Payments</h2>
            <table class='table_list'>
                <thead>
                    <tr>
                        <th>Payment</th>
                        <th>Category</th>
                        <th>Amount</th>
                        <th>Date Due</th>
                        <th>Recurring</th>
                        </tr>
                </thead>
                <tbody>
                    {% for payment in payment_list %}
                    <tr>
                        <td>{{ payment.name }}</td>
                        <td>{{ payemnt.category }}</td>
                        <td>{{ payment.amount }} </td>
                        <td>{{ payment.date_due }} </td>
                        <td>{{ payment.recurring }} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% comment %} <ul>
            {% for payment in payment_list %}
            <li>{{ payment.name}} </li>
            </ul>
            {% endfor %} {% endcomment %}
        </div>
    </main>
</body>
</html>

{% endblock %} 